### ISSUE TITLE
no content displayed after log in

### ISSUE THREAD

**Issue by plucian** [open-lims/open-lims#1]
it logs in and the top tabs are showing up (Home, Search...) but there is no content showing up. When clicked the tabs, it loads but nothing changes.
Using Apache24, php7.1, postgresql 9.4 and windows 7.
No errors are showing up.
![untitled](https://cloud.githubusercontent.com/assets/16140708/18548635/7d450e7e-7b52-11e6-966a-3efdf5b45a92.jpg)

**Comment by open-lims** [comment]
We didn't tested it with PHP 7.1. Do you have access to the PHP error log? It seems, that the module registration didn't work fine.

**Comment by plucian** [comment]
Here it is.
[error.txt](https://github.com/open-lims/open-lims/files/476718/error.txt)
What is the php version you're using now ? Still 3.5 ?

**Comment by open-lims** [comment]
We are using still PHP 5.3 or 5.4.  Some of the code does not work with PHP 7.1, it causes an fatal error. We will fix it in version 0.4.0.1.

**Comment by robertpuccinelli** [comment]
I saw that there were a few updates in the repository for version 0.4.0.1 a few months ago. Is it likely that it'll be released later this year or should I consider using the current version with an older version of PHP? Thanks for developing this

**Comment by open-lims** [comment]
After the last updates, it should run with PHP 7.1 but the change to PDO isn't complete yet. It is possible to use the current repository but you need PDO for PostgreSQL and the installer doesn't work (the database must be imported manually). The error reporting in the php.ini must be set to "E_ALL & ~ E_NOTICE" or lesser error reporting. We will finish the integration of PDO in the next month.
